# extract info generated by runAll.bat
import os

analysis_dir = os.path.join('..', 'target', 'analysis')

approaches = 'oo visitor visitorSideEffect extensibleVisitor interpreter coco trivially dispatch'
evolutions = 'M0 J1 J2 J3 J4 J5 J6 J7 J8 J5J8 J9 J10'

def zipFileSize(aip, eip):
    zf = aip + "-" + eip + "-src.zip"
    actual = os.path.join(analysis_dir, zf)
    return os.path.getsize(actual)

table = {}
for aip in approaches.split():
    for eip in evolutions.split():
        sz = zipFileSize(aip,eip)
        fmt = f'{aip:20} {eip:10} {sz:10}'
        if not aip in table:
            table[aip]= {}
        table[aip][eip] = sz

atitle='AIP'
header = f'{atitle:20}'
for eip in evolutions.split():
    header += f'{eip:7}'
    header += ' '

print (header)
for aip in approaches.split():
    row = f'{aip:20}' + ' '
    for eip in evolutions.split():
    
        sz = table[aip][eip]
        row += f'{sz:<7}'
        row += ' '
    print(row)
    
        
        
